version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: DB_Project_3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bigdata_network

  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - bigdata_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - bigdata_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - bigdata_network
    depends_on:
      - prometheus

volumes:
  postgres_data:

networks:
  bigdata_network:
